spring:
  cloud:
    gateway:
      routes:
      - id: book_route
        uri: http://localhost:8090
        predicates:
        - Path=/book/available/**
        filters:
        - RewritePath=/book/(?<segment>.*), /$\{segment}

management.endpoints.web.exposure.include: '*'                